name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.1.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: bazel
        run: buildifier -mode check -lint warn -r .
      - name: csharp
        run: dotnet format KRPC2.sln --verify-no-changes --exclude bazel-bin

  build-krpc2-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.1.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: fetch
        uses: krpc/krpc-core/.github/actions/bazel-fetch@main
      - name: libs
        env:
          KSP2_LIB_PASSWORD: ${{ secrets.KSP2_LIB_PASSWORD }}
        run: |
          wget https://krpc.s3.amazonaws.com/lib/ksp2-0.1.1.zip
          mkdir -p lib/ksp2/KSP2_x64_Data/Managed
          unzip -P "$KSP2_LIB_PASSWORD" ksp2-0.1.1.zip -d lib/ksp2
          rm ksp2-0.1.1.zip
      - name: build
        run: bazel build //:krpc2

  build-krpc2-windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: libs
        env:
          KSP2_LIB_PASSWORD: ${{ secrets.KSP2_LIB_PASSWORD }}
        shell: pwsh
        run: |
          $client = new-object System.Net.WebClient
          $client.DownloadFile("https://krpc.s3.amazonaws.com/lib/ksp2-0.1.1.zip", "ksp2-0.1.1.zip")
          mkdir lib/ksp2/KSP2_x64_Data/Managed
          7z.exe x ksp2-0.1.1.zip -o"lib/ksp2" -p"$env:KSP2_LIB_PASSWORD" -y
          del ksp2-0.1.1.zip
      - name: build
        run: bazel --bazelrc=.github/workflows/bazelrc build //:krpc2

  build-krpc2-sln-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.1.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: fetch
        uses: krpc/krpc-core/.github/actions/bazel-fetch@main
      - name: libs
        env:
          KSP2_LIB_PASSWORD: ${{ secrets.KSP2_LIB_PASSWORD }}
        run: |
          wget https://krpc.s3.amazonaws.com/lib/ksp2-0.1.1.zip
          mkdir -p lib/ksp2/KSP2_x64_Data/Managed
          unzip -P "$KSP2_LIB_PASSWORD" ksp2-0.1.1.zip -d lib/ksp2
          rm ksp2-0.1.1.zip
      - name: deps
        run: bazel build //:csproj
      - name: build
        run: dotnet build KRPC2.sln

  build-krpc2-sln-windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: libs
        env:
          KSP2_LIB_PASSWORD: ${{ secrets.KSP2_LIB_PASSWORD }}
        shell: pwsh
        run: |
          $client = new-object System.Net.WebClient
          $client.DownloadFile("https://krpc.s3.amazonaws.com/lib/ksp2-0.1.1.zip", "ksp2-0.1.1.zip")
          mkdir lib/ksp2/KSP2_x64_Data/Managed
          7z.exe x ksp2-0.1.1.zip -o"lib/ksp2" -p"$env:KSP2_LIB_PASSWORD" -y
          del ksp2-0.1.1.zip
      - name: deps
        run: bazel --bazelrc=.github/workflows/bazelrc build //:csproj
      - name: build
        run: dotnet build KRPC2.sln
